# Generated by Django 4.2.3 on 2023-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='visable',
            field=models.BooleanField(default=True),
        ),
    ]
