# Generated by Django 4.2.3 on 2023-07-24 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora_app', '0002_alter_questions_visable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('author', 'question')},
        ),
    ]
