# Generated by Django 4.2.3 on 2023-07-24 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora_app', '0003_alter_answers_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('author', 'answer')},
        ),
    ]
